@enum Mode begin
    dDDI = Int(API.AMGX_mode_dDDI)
    dDFI = Int(API.AMGX_mode_dDFI)
    dFFI = Int(API.AMGX_mode_dFFI)
    hIDI = Int(API.AMGX_mode_hIDI)
    hIFI = Int(API.AMGX_mode_hIFI)
    dIDI = Int(API.AMGX_mode_dIDI)
    dIFI = Int(API.AMGX_mode_dIFI)
    hZZI = Int(API.AMGX_mode_hZZI)
    hZCI = Int(API.AMGX_mode_hZCI)
    hCCI = Int(API.AMGX_mode_hCCI)
    dZZI = Int(API.AMGX_mode_dZZI)
    dZCI = Int(API.AMGX_mode_dZCI)
    dCCI = Int(API.AMGX_mode_dCCI)
end
